version: '2'
services:
  configserver:
    image: test/config-microservices
    restart: always
    ports:
      - "8888:8888"
  discovery:
    image: test/euricaserver
    ports:
       - "8761:8761"
    restart: always
    links:
       - configserver
  gateway:
    image: test/gateway
    restart: always
    links:
      - discovery
      - configserver
      - newsservice
      - userservice
    ports:
      - "4000:4000"
    depends_on:
      - "discovery"
      - "configserver"
  mongo-db:
    image: mongo:latest
    ports:
        - "27017:27017"
    restart: always
  newsservice:
    image: test/newsmongoserviece
    ports:
        - "9098:9098"
    restart: always
    links:
        - discovery
        - configserver
        - mongo-db
  postgres:
    image: postgres:latest
    ports:
        - "5432:5432"
    restart: always
    environment:
        - POSTGRES_USER:'postgres'
        - POSTGRES_PASSWORD:'admin'
  userservice:
    image: test/userservice
    ports:
            - "9090:9090"
    restart: always
    links:
          - discovery
          - configserver
          - postgres